### ISSUE TITLE
Deprecate `make requirements`

### ISSUE THREAD

**Issue by acwooding** [hackalog/cookiecutter-easydata#110]
I accidentally used `make requirements` instead of `make update_environment`. It still sort of did something. But then make got into a crazy place:

`/bin/sh: fork: retry: No child processes
/bin/sh: fork: retry: No child processes
/bin/sh: fork: retry: No child processes
/bin/sh: fork: retry: No child processes
/bin/sh: fork: retry: No child processes
/bin/sh: fork: retry: No child processes
/bin/sh: fork: retry: No child processes
make[1179]: Makefile.include:1: fork: Resource temporarily unavailable
make[1179]: Makefile.include:4: fork: Resource temporarily unavailable
make[1179]: Makefile.include:1: fork: Resource temporarily unavailable
make[1179]: Makefile.include:4: fork: Resource temporarily unavailable
make[1179]: vfork: Resource temporarily unavailable
make[1179]: Makefile.include:1: fork: Resource temporarily unavailable
make[1179]: Makefile.include:4: fork: Resource temporarily unavailable
make[1179]: Makefile.include:1: fork: Resource temporarily unavailable
make[1179]: Makefile.include:4: fork: Resource temporarily unavailable
make[1179]: vfork: Resource temporarily unavailable`

and so on...

**Comment by hackalog** [comment]
Hm. They should be the same. Looks like a fork bomb. Did i somehow cause a
dependency loop?
Will look. What does `make -n requirements` Say it does?

**Comment by acwooding** [comment]
```
python3 test_environment.py
/opt/software/anaconda3/bin/conda env update -n embedallthethings2 -f environment.yml
/opt/software/anaconda3/bin/conda env export -n embedallthethings2 -f environment.x86_64.lock.yml
# pip install -e .  # uncomment for conda <= 4.3
echo "WARNING: `make requirements` is deprecated. Use `make update_environment`"
```

**Comment by hackalog** [comment]
Hahah. Too much markdown for me. Easy fix.  All those backticks need to be
changed to regular single quotes.
