### ISSUE TITLE
Remove call to hash_file in datasets.py

### ISSUE THREAD

**Issue by acwooding** [hackalog/cookiecutter-easydata#113]
`hash_file` is deprecated, and no longer needed in `add_file` as the hash is computed in the fetch step.
```
        if hash_value is None:
            logger.debug(f"Hash unspecified. Computing {hash_type} hash of {source_file.name}")
            hash_value = hash_file(source_file, algorithm=hash_type).hexdigest()
```

**Comment by hackalog** [comment]
Is it deprecated? This has the nice benefit of throwing a warning that you didn't specify a hash....
(it can be included from `fetch.py` to avoid the error)
