### ISSUE TITLE
Have an option for a "metadata-only" unpack step

### ISSUE THREAD

**Issue by acwooding** [hackalog/cookiecutter-easydata#119]
No need to expand a .zip file or some tarballs on disk if using pandas .read_csv. Probably need an option to NOT unpack if we're using pandas for our processing of data. It would be nice to not eat up so much disk space. Maybe have the option to ONLY unpack metadata somehow.

**Comment by hackalog** [comment]
Oh, because read_csv will reach into the zipfile. I see.
Hm. This would mean maintaining an explicit *unpack_action* for each file. (I suppose it could default based on the file extension)...
