### ISSUE TITLE
Hint in docs to symlink your data dir

### ISSUE THREAD

**Issue by acwooding** [hackalog/cookiecutter-easydata#120]
Give instructions/hint in the docs that you may want to link your data dir to somewhere else. I forgot to do this and had to go back and symlink it.

**Comment by hackalog** [comment]
I kind of want Makefile.envs to be useful across multiple projects (and that's the logical place to add it).
What if we add a post-create banner? i.e. a textfile that, if present, will be displayed after the environment is created?

something like `.post-create-environment.txt`?

**Comment by hackalog** [comment]
See #129 for my proposed fix
