### ISSUE TITLE
Catalog includes my local paths

### ISSUE THREAD

**Issue by acwooding** [hackalog/cookiecutter-easydata#121]
Hmmm...the catalogs makes explicit reference to locations on MY machine (eg. https://github.com/acwooding/embedallthethings2/blob/master/catalog/datasources.json). I'm using catalog to script the process of creating datasources, so that someone else can set them up by simply running `make data` as long as they have access to the same raw data. Something isn't right with this design. 

Another problem related to this is that I want to use version control on my catalog, which also means that I'm checking in my local paths. (This is extremely useful as it is so easy to accidentally corrupt the catalogue and then it's nice to revert to the last version of it...we probably also want a way to prevent corruption of the catalog).

Options include:
* find a way to json serialize the instructions in a non-machine dependent kind of way
* create a script to regenerate the catalog

This is a design question as much as anything else right now, but it doesn't "do" what I want it to do yet.

**Comment by hackalog** [comment]
The paths (`raw_data_path`, etc) can be different on a different machine,
and make data should work just fine.  I'm not sure I understand what's
broken. Where are the machine dependencies or hardcoded paths? (yes, they
should all be relative to the location in `src.paths`

**Comment by hackalog** [comment]
Yes, this requires some thinking. paths is currently a json dump, but it might make sense to use a configparser format so that we can embed a filename base.

Also, the default behavior should be relative to the src module location, so there has to be a way to specify that.

**Comment by hackalog** [comment]
Looks like one of the main problems is the `add_file()` method, in particular, the source path, which is almost never reproducible. I'll add an `add_message()` method, which will display a message indicating how to obtain the file, and that should handle a bunch of the use cases
