### ISSUE TITLE
Remove python2 support

### ISSUE THREAD

**Issue by acwooding** [hackalog/cookiecutter-easydata#41]

**Comment by haugstve** [comment]
Removing python 2 seems to be worth the effort. It is nice with flexibility but right noe I feel the barrier to start using the cookiecutter template is a bit too high for Data Scientists used to only working in notebooks.

I'm willing to give it a try, if pull requests are welcome.

**Comment by hackalog** [comment]
@haugstve pull requests are always welcome! This one, however, is fixed as of 20200206 :) Sorry for not replying sooner
