### ISSUE TITLE
Add the option to update

### ISSUE THREAD

**Issue by acwooding** [hackalog/cookiecutter-easydata#61]
Add a flag --update repo_name (for example) that allows you to update the underlying cookicutter-easydata framework

**Comment by hackalog** [comment]
This is getting a lot easier, as I've added replay in #127, so we can now do a
```
cookiecutter --config-file repo_name/cookiecutter-easydata.yaml cookiecutter-easydata -f
```
and the module will be regenerated in place. 

I think the best step after this is to give a little script to automatically create a branch and start a merge, since you'll inevitably have to solve a 3-way merge here.

**Comment by hackalog** [comment]
Some others discussing this very idea:
* https://github.com/cookiecutter/cookiecutter/issues/784
Some implementations of this idea
* https://github.com/senseyeio/cupper (based on the below)
* https://github.com/aroig/cookiecutter-latex-paper/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/make/cookiecutter-update.py (uses `update-template target, below`)
* https://github.com/aroig/cookiecutter-latex-paper/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile (see `update-template` target)

**Comment by hackalog** [comment]
So, I have a working git procedure to make this work. 
We could incorporate the linked scripts above, but that would increase our git dependency to a later version (to support git worktree). Since this is presumably not a common thing to do, it can be worked around with documentation (the git operations) for now.

**Comment by hackalog** [comment]
I should note, there's also this approach (a PR against cookiecutter directly). 
https://github.com/cookiecutter/cookiecutter/pull/1173/files

**Comment by hackalog** [comment]
I've written up a howto for now
https://github.com/hackalog/cookiecutter-easydata/wiki/Merging-Easydata-Changes-into-a-Generated-Project

**Comment by hackalog** [comment]
I've moved the links above into the [Merging Easydata Changes wiki page](https://github.com/hackalog/cookiecutter-easydata/wiki/Merging-Easydata-Changes-into-a-Generated-Project). Closing this unless automation becomes an issue.
