### ISSUE TITLE
Catalog file datasources.json to make raw

### ISSUE THREAD

**Issue by wbashir** [hackalog/cookiecutter-easydata#97]
Hi, 

Thanks for making this great template and I apologize if I am jumping in early. I am trying to execute the `make source` command and failing. I've defined the `catalog/datasources.json`:

````
{
"name": "test",
"url_list": []
}
````
<img width="513" alt="screen shot 2019-03-01 at 4 39 19 pm" src="https://user-images.githubusercontent.com/825838/53671198-f2c4c280-3c42-11e9-84bb-a10d97a9067e.png">

**Comment by hackalog** [comment]
Hi @wbashir !

You may find it easier to define the datasources using the tools in  `workflow.py`
In this case, `catalog/datasources.json` needs to be a dict of dicts, one per datasource. 

off the top of my head, something like:
```
{
 "test": {
    "name": "test",
    "url_list": []
  }
}
```

I'd recommend you try running through the first couple of notebooks in the Bus Number tutorial: https://github.com/hackalog/bus_number/ 

In particular, start a project with 
`cookiecutter https://github.com/hackalog/cookiecutter-easydata.git --checkout bus_number`
and work through the first couple of notebooks. (notebook 20 covers creating data sources and adding them to the catalog).

Note that we are running a group through the tutorial right now, so we are making minor tweaks pretty much daily. the first two notebooks (10 and 20) are pretty solid, and 22 is getting very close to its final form.  Beyond that, I'd wait at least a week...

**Comment by wbashir** [comment]
`You may find it easier to define the datasources using the tools in workflow.py`

What is the recommended approach for the datasource creation process when working with `workflow.py`, should we script or build as Jupyter Notebooks (similar to the tutorial)?

**Comment by hackalog** [comment]
I like building a notebook, because it gives me automatic documentation for my EDA on the raw data. When I come back to it 6 months later, I don't have to rediscover all the gotchas of that particular data format.
